export enum ActionTypes {
    GET_CATEGORIES = 'GET_CATEGORIES',
    ADD_CATEGORY = 'ADD_CATEGORY',
    UPDATE_CATEGORY = 'UPDATE_CATEGORY',
    DELETE_CATEGORY = 'DELETE_CATEGORY',
}

export enum GetterTypes {
    CATEGORY_LIST = 'CATEGORY_LIST',
}

export enum MutationTypes {
    RESET = 'RESET',
    SET_CATEGORIES = 'SET_CATEGORIES',
    ADD_CATEGORY = 'ADD_CATEGORY',
    REPLACE_CATEGORY = 'REPLACE_CATEGORY',
    DELETE_CATEGORY = 'DELETE_CATEGORY',
}
